### ISSUE TITLE
Build active_directory.h as a separate solib?

### ISSUE THREAD

**Issue by NIR-Ginko** [altlinux/admc#12]
Subj.

**Comment by NIR-Ginko** [comment]
Cast @mastersin , @Kvel2D

**Comment by mastersin** [comment]
Ну, это не горит, достаточно перенести файлы в отдельный каталог. Вообще, solib полезен для дополнительной cli. Рассчитывал заняться детально архитектурой после того, как будет минимальный набор фич.

**Comment by NIR-Ginko** [comment]
@mastersin , да оно вроде уже вырисовывается. Оно же умеет подключаться к домену? Если да, то можно заниматься. Алсо посмотри мой PR на CMake. Если сольём, то я дальше организую выделение этого добра в отдельную библиотеку.

**Comment by Kvel2D** [comment]
Btw, that active_directory lib is the best one I've found after a quick search and is not ideal. It's from 2002, uses deprecated functions and doesn't handle paging. Could update it ourselves or find a better replacement if possible.
I've found this one: https://github.com/paleg/libadclient
But it's not perfect either. No guarantees about it's quality and it converts to c++ containers when we need Qt containers so we'll have double conversions for no reason. Also uses exceptions.

**Comment by NIR-Ginko** [comment]
@Kvel2D , I think that C implementation is nice and it's simpler to build solib out of C code. We may peek at the code you've mentioned (luckily, it's not a big project) and build a library that fits our needs.

**Comment by NIR-Ginko** [comment]
I don't have any prejudice about exceptions except that I'm afraid to use C++ code in projects implemented in other programming languages because we'll need proper C++ exception handling.

**Comment by Kvel2D** [comment]
Seems to be done?
