### ISSUE TITLE
Specify domain controller's name in UI.

### ISSUE THREAD

**Issue by august-alt** [altlinux/admc#142]
When using ADUC user can see current domain controller he is connected to. ADUC also provide user with ability to switch domain controller, it would be great if we can provide our users with similar functionality.

**Comment by Kvel2D** [comment]
https://github.com/altlinux/admc/blob/4c480efc309606088992ad12f419be0b312404e0/src/admc/ad_interface.cpp#L111

Domain controller string is available inside AdInterface::connect(). It comes as a result of get_domain_hosts() call. Can save it there to AdInterface instance and then insert it somewhere in the UI.

One problem is that ADUC places domain string at the top node that represents the app itself. It's above the domain object. ADMC doesn't have that node, so need to think about where to put domain controller string. It's not that important at this point, can always move it to another spot later.
