### ISSUE TITLE
Altlinux p9, not connected to AD, need more debug

### ISSUE THREAD

**Issue by x09** [altlinux/admc#222]
Tried admc (p9 repo)

Logged in as a domain user. Kerberos ticket is valid. But admc not connected.

![2021-06-21_17-28](https://user-images.githubusercontent.com/1303927/122762095-637dc600-d2b6-11eb-8fd4-5e03505369d3.png)

ldapsearch work fine

`ldapsearch -L -b 'OU=ГКУ ЦИТТО,OU=Советская 61,DC=adm72,DC=local' -H ldap://my-pdc.adm72.local:3268 -Y GSSAPI '(&(SAMAccountName=mylogin)(!(objectClass=computer)))' userAccountControl pwdLastSet`

How enable more debug verbose. admc have a config file (to specify AD host, port, tls, ssl)?

**Comment by Kvel2D** [comment]
Hello,

Newer version of ADMC (0.5.3) has more detailed messages about connection errors but this version is not in p9 repo yet. You could build ADMC yourself or download the package from this test-only task: 274869. Let me know if you need instructions on how to do this.

**Comment by x09** [comment]
i build myself.. run admc, but segmentation fault every time.. i remove it. 
apt-repo add task 274869 && apt-get install admc..

$ rpm -ql admc 
```
/usr/bin/admc
/usr/lib64/libadldap.so
/usr/share/doc/admc-0.5.3
/usr/share/doc/admc-0.5.3/README.md
/usr/share/doc/admc/admc.qch
/usr/share/man/man1/admc.1.xz
```
$ admc
```
Failed to find manual file. Check that program was installed correctly. (If you are a developer and want to load uninstalled help file from source, set build type to debug.
Ошибка сегментирования
```

Something went wrong..

**Comment by Kvel2D** [comment]
Can you run this:

`catchsegv ./admc > admc_segv_log`

And then attach `admc_segv_log` file here?

**Comment by x09** [comment]
admc from task

[admc_from_task.log](https://github.com/altlinux/admc/files/6692424/admc_from_task.log)

**Comment by Kvel2D** [comment]
Can you pull the latest version and rebuild and run it again? I think I fixed the problem in this commit: a0807e979b45f5dcf0264795129cda3b42f42b54.

I think what you should get now is the "Failed to get a domain" which is better than a segfault...

**Comment by Kvel2D** [comment]
This commit 7954353bdd67f310f36a187b7243e3e46e82b15a should also fix "Failed to get a domain" error message and hopefully you'll be able to connect.

**Comment by x09** [comment]
> This commit [7954353](https://github.com/altlinux/admc/commit/7954353bdd67f310f36a187b7243e3e46e82b15a) should also fix "Failed to get a domain" error and hopefully you'll be able to connect.

Worked!

**Comment by x09** [comment]
worked 3 minutes... and again "Ошибка сегментирования" or see screenshot.. 
![2021-06-22_14-44](https://user-images.githubusercontent.com/1303927/122902999-69cc7a80-d368-11eb-8945-f4c91c4a7b01.png)

**Comment by Kvel2D** [comment]
If the app opened but then failed to connect later then there might be a problem with the connection to the server. Segmentation faults most likely happen due to the app working incorrectly after failing to connect. This is because ADMC hasn't been tested enough in unstable connection environments yet.

Can you give some info about your connection? Is the domain server running on Windows or Samba? Are there connection problems in other programs?

**Comment by x09** [comment]
> If the app opened but then failed to connect later then there might be a problem with the connection to the server. Segmentation faults most likely happen due to the app working incorrectly after failing to connect. This is because ADMC hasn't been tested enough in unstable connection environments yet.
> 
> Can you give some info about your connection? Is the domain server running on Windows or Samba? Are there connection problems in other programs?

Windows. AD. No problems in other apps

i wrote mail to kevl@altlinux ;)

**Comment by Kvel2D** [comment]
Replaced by #224
