### ISSUE TITLE
Missing "Protect against deletion" feature

### ISSUE THREAD

**Issue by yamah-byv** [altlinux/admc#283]
Samba DC AD на Альт 9 Сервер
ADMC на Альт 10 (Аль 9 десктоп обновлен до Альт 10).

При удалении OU возникает ошибка разрешения на удаление 
Причина проблемы.
OU автоматически блокируются от удаления. Для разблокировки необходимо убрать отметку с чекпоинт о блокировки объекта. В RSAT он находится на вкладке Object. Аналогичного чекпоинта в ADMC не было обнаружено.

С Уважением, Ярослав Белых

**Comment by Kvel2D** [comment]
(translation)
This feature is available as a checkbox in "Object" tab in Properties dialog for objects. It is also available in creation dialog for OU's. Currently in ADMC can't delete protected objects because can't turn off this protection.
