### ISSUE TITLE
Icons are broken for Shared folders

### ISSUE THREAD

**Issue by Mariafokanova** [altlinux/admc#352]
![admc-icons-001](https://user-images.githubusercontent.com/74016580/159483999-444e84c3-7283-4bf7-b4cf-94439f786fee.png)
![admc-icons-002](https://user-images.githubusercontent.com/74016580/159484002-2667d5be-bc9c-478a-86fa-14c9cc51fc0e.png)
Virtual Box, ALT Workstation 10, ADMC 0.9.0-alt1.x86_64

**Comment by Kvel2D** [comment]
This is already fixed in c65ad186995c59cc7c23891b1aa09ee7f46bbec2. Ability to create shared folders and icons for shared folders were added during the pre-release of 0.9.0. Please wait for the full release.
