### ISSUE TITLE
Setting user's password in ADMC not working

### ISSUE THREAD

**Issue by NIR-Ginko** [altlinux/admc#72]
There is no direct way to set password in LDAP. We need to look at https://github.com/altlinuxteam/hadfs implementation using specific RPC for setting password or encode password in acceptable way.

**Comment by Kvel2D** [comment]
What didn't work? Currently ADMC sets the password the same way as adldap(which I assume you meant instead of hadfs).
`adSetUserPass :: ADCtx -> DN -> Text -> IO ()
adSetUserPass ad dn' pass = ldapModify (ldap ad) (T.unpack . unTagged $ dn') [LDAPMod LdapModReplace "unicodePwd" [encodedPass]]
  where quotedPass = "\"" `T.append` pass `T.append` "\""
        encodedPass = (BC.unpack . T.encodeUtf16LE) quotedPass
`
`bool AdInterface::user_set_pass(const QString &dn, const QString &password) {
    const QByteArray dn_array = dn.toLatin1();
    const char *dn_cstr = dn_array.constData();

    const QString quoted_password = QString("\"%1\"").arg(password);
    const QByteArray quoted_password_array = quoted_password.toLatin1();
    const char *quoted_password_cstr = quoted_password_array.constData();
    const int unicode_password_length = quoted_password.length() * 2;
    char unicode_password_cstr[unicode_password_length];
    memset(unicode_password_cstr, 0, sizeof(unicode_password_cstr));
    for (int i = 0; i < quoted_password.length(); i++) {
        unicode_password_cstr[i * 2] = quoted_password_cstr[i];
    }

    const int result = ad_attribute_replace_binary(ld, dn_cstr, ATTRIBUTE_PASSWORD, unicode_password_cstr, unicode_password_length);`

**Comment by mastersin** [comment]
Well I tried this yesterday and my password didn't work for the new user either after creating it or after resetting the password.

**Comment by Kvel2D** [comment]
Can you provide more details, specific error message for example. For me creating user and logging in through PVE worked.

**Comment by Kvel2D** [comment]
I did notice that Russian characters are not processed correctly for passwords, fixing that now.

**Comment by Kvel2D** [comment]
Fixed Russian chars in passwords in ea32f6c083a61a2d73b728bc0ad97ee7ba7867ef.
@mastersin still need more details about what went wrong, error messages, etc.
