### ISSUE TITLE
libresolv underlinking

### ISSUE THREAD

**Issue by NIR-Ginko** [altlinux/admc#76]
I've met this warning during ADMC build in Hasher:

```
lib.req: WARNING: /usr/src/tmp/admc-buildroot/usr/lib64/libadldap.so: underlinked libraries: /lib64/libresolv.so.2
```

It is needed to investigate roots of the problem

**Links**:
https://wiki.mageia.org/en/Overlinking_issues_in_packaging
https://wiki.mageia.org/en/Underlinking_issues_in_packaging

**Comment by Kvel2D** [comment]
/lib64/libresolv.so is provided by glibc-devel. Forgot to add it.

**Comment by Kvel2D** [comment]
16a9d70583658ffb85eb0e4346cca63af4685f49 should've fixed it. I didn't get any underlinking.
