### ISSUE TITLE
Authentication problems

### ISSUE THREAD

**Issue by NIR-Ginko** [altlinux/admc#78]
When logging into domain using login dialog I've got SIGABRT with the following data:

```
admc: search.c:95 ldap_pvt_search: Проверочное утверждение "ld != NULL" не выполнено.
```

The error comes from 
![IMG_20201009_175624](https://user-images.githubusercontent.com/505327/95592555-da8d6a00-0a59-11eb-832e-cb52ddb32e3f.jpg)

**Comment by NIR-Ginko** [comment]
This may be a bug in my branch only. Investigating.

**Comment by Kvel2D** [comment]
Can you publish your branch so I can take a look?
