### ISSUE TITLE
Separate headers from sources

### ISSUE THREAD

**Issue by NIR-Ginko** [altlinux/admc#9]
Subj. is a bad practice leading to problems in the future.

**Comment by Kvel2D** [comment]
https://stackoverflow.com/questions/13967296/why-place-headers-in-a-separate-directory
https://stackoverflow.com/questions/2924037/separate-include-and-src-folders-for-application-level-code

From what I've read online this doesn't seem beneficial. Putting public headers into 'include' folder sounds okay but there are no public headers yet (maybe won't be at all?). If anything, creating sub directories in 'src' to separate "by theme" sounds better.

**Comment by NIR-Ginko** [comment]
Qt5 allows to write rather modular code so dialog windows you implement may become sub-windows of another system in a moment making your interface looking like library. Thinking ahead of the problem: We're developing complex application so you might expect multiple modules with their interconnection. Attempt to include header files from another module with `*.cpp`s scattered around is not very nice.

**Comment by NIR-Ginko** [comment]
Cast @mastersin

**Comment by Kvel2D** [comment]
Qt5 moc/cmake doesn't deal well with headers and sources separated. If a class contains Q_OBJECT macro it just won't compile.
